version: "3.2"
services:
  multiplayer-api:
    build:
      context: https://github.com/DmytroCh/game-back-end.git#master
    ports:
      - "3001:3001"
  multiplayer-ui:
    build:
      context: https://github.com/DmytroCh/game-front-end.git#master
    depends_on:
      - multiplayer-api
    ports:
      - "3000:3000"
    environment:
      - "API_URL=http://vmi473672.contaboserver.net:3001"

